export interface ZodiacSign {
  name: string;
  symbol: string;
  glyph: string;
  dates: string;
  element: "Fire" | "Earth" | "Air" | "Water";
  planet: string;
  traits: string[];
  description: string;
  color: string;
  accentColor: string;
  compatibility: string[];
}

export const zodiacSigns: ZodiacSign[] = [
  {
    name: "Aries",
    symbol: "♈",
    glyph: "♈",
    dates: "Mar 21 – Apr 19",
    element: "Fire",
    planet: "Mars",
    traits: ["Courageous", "Determined", "Passionate", "Impulsive"],
    description: "Bold and ambitious, Aries dives headfirst into even the most challenging situations.",
    color: "#8B1A1A",
    accentColor: "#FF4444",
    compatibility: ["Leo", "Sagittarius", "Gemini"],
  },
  {
    name: "Taurus",
    symbol: "♉",
    glyph: "♉",
    dates: "Apr 20 – May 20",
    element: "Earth",
    planet: "Venus",
    traits: ["Reliable", "Patient", "Practical", "Stubborn"],
    description: "Taurus is an earth sign represented by the bull, reflecting their tenacious and resolute nature.",
    color: "#1A4A1A",
    accentColor: "#4CAF50",
    compatibility: ["Virgo", "Capricorn", "Cancer"],
  },
  {
    name: "Gemini",
    symbol: "♊",
    glyph: "♊",
    dates: "May 21 – Jun 20",
    element: "Air",
    planet: "Mercury",
    traits: ["Versatile", "Curious", "Affectionate", "Indecisive"],
    description: "Expressive and quick-witted, Gemini represents two different personalities in one and you will never be sure which one you will face.",
    color: "#1A3A5A",
    accentColor: "#64B5F6",
    compatibility: ["Libra", "Aquarius", "Aries"],
  },
  {
    name: "Cancer",
    symbol: "♋",
    glyph: "♋",
    dates: "Jun 21 – Jul 22",
    element: "Water",
    planet: "Moon",
    traits: ["Tenacious", "Imaginative", "Loyal", "Moody"],
    description: "Intuitive and sentimental, Cancer can be one of the most challenging zodiac signs to get to know.",
    color: "#1A1A4A",
    accentColor: "#9C88C8",
    compatibility: ["Scorpio", "Pisces", "Taurus"],
  },
  {
    name: "Leo",
    symbol: "♌",
    glyph: "♌",
    dates: "Jul 23 – Aug 22",
    element: "Fire",
    planet: "Sun",
    traits: ["Creative", "Passionate", "Generous", "Arrogant"],
    description: "Represented by the lion, Leo is the king of the celestial jungle. These spirited fire signs are the zodiac's leaders.",
    color: "#4A2A00",
    accentColor: "#FFB347",
    compatibility: ["Aries", "Sagittarius", "Gemini"],
  },
  {
    name: "Virgo",
    symbol: "♍",
    glyph: "♍",
    dates: "Aug 23 – Sep 22",
    element: "Earth",
    planet: "Mercury",
    traits: ["Analytical", "Loyal", "Hardworking", "Overly-critical"],
    description: "Smart, sophisticated, and kind, Virgo gets the job done without complaining. Virgos are dedicated to the craft.",
    color: "#1A3A1A",
    accentColor: "#81C784",
    compatibility: ["Taurus", "Capricorn", "Cancer"],
  },
  {
    name: "Libra",
    symbol: "♎",
    glyph: "♎",
    dates: "Sep 23 – Oct 22",
    element: "Air",
    planet: "Venus",
    traits: ["Diplomatic", "Gracious", "Idealistic", "Indecisive"],
    description: "Libra is obsessed with symmetry and strives to create equilibrium in all areas of life.",
    color: "#3A1A4A",
    accentColor: "#CE93D8",
    compatibility: ["Gemini", "Aquarius", "Leo"],
  },
  {
    name: "Scorpio",
    symbol: "♏",
    glyph: "♏",
    dates: "Oct 23 – Nov 21",
    element: "Water",
    planet: "Pluto",
    traits: ["Brave", "Loyal", "Ambitious", "Jealous"],
    description: "Scorpio is one of the most misunderstood signs of the zodiac. It's not a darkness, but rather depth.",
    color: "#3A0A0A",
    accentColor: "#EF5350",
    compatibility: ["Cancer", "Pisces", "Virgo"],
  },
  {
    name: "Sagittarius",
    symbol: "♐",
    glyph: "♐",
    dates: "Nov 22 – Dec 21",
    element: "Fire",
    planet: "Jupiter",
    traits: ["Generous", "Idealistic", "Great Humor", "Impatient"],
    description: "Curious and energetic, Sagittarius is one of the biggest travelers among all zodiac signs.",
    color: "#3A1A00",
    accentColor: "#FF8C00",
    compatibility: ["Aries", "Leo", "Aquarius"],
  },
  {
    name: "Capricorn",
    symbol: "♑",
    glyph: "♑",
    dates: "Dec 22 – Jan 19",
    element: "Earth",
    planet: "Saturn",
    traits: ["Responsible", "Disciplined", "Self-control", "Stubborn"],
    description: "Capricorn is a sign that represents time and responsibility, and its representatives are traditional and often very serious by nature.",
    color: "#1A1A1A",
    accentColor: "#90A4AE",
    compatibility: ["Taurus", "Virgo", "Scorpio"],
  },
  {
    name: "Aquarius",
    symbol: "♒",
    glyph: "♒",
    dates: "Jan 20 – Feb 18",
    element: "Air",
    planet: "Uranus",
    traits: ["Progressive", "Original", "Independent", "Aloof"],
    description: "Despite the 'aqua' in its name, Aquarius is actually the last air sign of the zodiac. A rebel at heart.",
    color: "#003A4A",
    accentColor: "#00BCD4",
    compatibility: ["Gemini", "Libra", "Sagittarius"],
  },
  {
    name: "Pisces",
    symbol: "♓",
    glyph: "♓",
    dates: "Feb 19 – Mar 20",
    element: "Water",
    planet: "Neptune",
    traits: ["Compassionate", "Artistic", "Intuitive", "Overly-trusting"],
    description: "Pisces is the most intuitive, sensitive, and empathetic sign of all the zodiac—and that's because it's the last of the last.",
    color: "#001A3A",
    accentColor: "#5C85D6",
    compatibility: ["Cancer", "Scorpio", "Taurus"],
  },
];

export const horoscopes: Record<string, string> = {
  Aries: "The cosmos ignites your ambitions today. A bold decision you've been postponing becomes crystal clear under Mars's fierce light. Trust your instincts — the universe rewards those who leap.",
  Taurus: "Venus whispers of abundance. Financial opportunities emerge from unexpected conversations. Ground yourself in what truly matters — your steady nature is your greatest asset.",
  Gemini: "Mercury energizes your mind with dazzling clarity. Two paths diverge before you, but your dual nature sees the beauty in both. Communication opens unexpected doors today.",
  Cancer: "The Moon bathes you in silver intuition. Emotional currents run deep — listen to what your body knows before your mind does. Home and family bring unexpected joy.",
  Leo: "The Sun amplifies your natural radiance. Creative projects flourish under your focused attention. Your generosity today creates ripples that return as waves of abundance.",
  Virgo: "Details reveal themselves with crystalline precision today. A project once confusing suddenly makes perfect sense. Your analytical gifts solve what others call unsolvable.",
  Libra: "Venus and Jupiter align to bring harmony to long-standing tensions. Beauty presents itself in unusual forms. An important relationship reaches a turning point of grace.",
  Scorpio: "Pluto stirs hidden depths. Truths buried beneath the surface rise to greet you. Transformation isn't comfortable, but what you're becoming is extraordinary.",
  Sagittarius: "Jupiter expands your horizons in unexpected directions. A journey — physical or philosophical — rewrites your understanding of possibility. Embrace the unknown.",
  Capricorn: "Saturn rewards your patience with concrete results. A long-term effort finally shows its fruits. Your discipline has been planting seeds — now watch them bloom.",
  Aquarius: "Uranus sparks revolutionary thinking. An unconventional idea you've dismissed deserves a second look. Your vision of the future is needed more than you know.",
  Pisces: "Neptune dissolves the boundary between dream and reality. Creative visions arrive with startling clarity. Trust the whispers from the deep — they carry ancient wisdom.",
};

export const elementColors = {
  Fire: { bg: "rgba(180, 40, 0, 0.15)", border: "rgba(255, 120, 50, 0.3)", text: "#FF8C50" },
  Earth: { bg: "rgba(20, 100, 20, 0.15)", border: "rgba(80, 180, 80, 0.3)", text: "#80C880" },
  Air: { bg: "rgba(20, 60, 140, 0.15)", border: "rgba(80, 140, 220, 0.3)", text: "#80B4E8" },
  Water: { bg: "rgba(40, 20, 120, 0.15)", border: "rgba(100, 80, 200, 0.3)", text: "#9088D8" },
};
